name: Deploy to VPS

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed
env:
  SSH_USER: d61e9e70cc1148129a64437afb2df91c
  SSH_HOST: d61e9e70cc1148129a64437afb2df91c
  PROJECT_DIR: d61e9e70cc1148129a64437afb2df91c

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: d61e9e70cc1148129a64437afb2df91c

      - name: Deploy to VPS via SSH
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << EOF
            set -e
            cd $PROJECT_DIR
            git fetch origin
            git checkout main
            git pull origin main
          EOF